FROM jenkins:latest
#JENKINS DE GBB

USER root
RUN mkdir /var/log/jenkins
RUN mkdir /var/cache/jenkins
RUN chown -R  jenkins:jenkins /var/log/jenkins
RUN chown -R  jenkins:jenkins /var/cache/jenkins

USER jenkins

ENV JAVA_OPTS="-Xmx4096m -Djenkins.install.runSetupWizard=false"
ENV JENKINS_OPTS="--logfile=/var/log/jenkins/jenkins.log --webroot=/var/cache/jenkins/war"

#installing plugins
COPY plugins.txt /usr/share/jenkins/ref/plugins.txt
RUN /usr/local/bin/install-plugins.sh < /usr/share/jenkins/ref/plugins.txt

#applying security
COPY security.groovy /usr/share/jenkins/ref/init.groovy.d/security.groovy

#adding Maven installations
COPY hudson.tasks.Maven.xml /usr/share/jenkins/ref/hudson.tasks.Maven.xml

#adding Gradle installations
COPY hudson.plugins.gradle.Gradle.xml /usr/share/jenkins/ref/hudson.plugins.gradle.Gradle.xml

#adding Ant installations
COPY hudson.tasks.Ant.xml /usr/share/jenkins/ref/hudson.tasks.Ant.xml

#adding JIRA configuration
COPY hudson.plugins.jira.JiraProjectProperty.xml /usr/share/jenkins/ref/hudson.plugins.jira.JiraProjectProperty.xml
COPY scriptApproval.xml /usr/share/jenkins/ref/scriptApproval.xml
COPY identity.key.enc /usr/share/jenkins/ref/identity.key.enc
COPY hudson.plugins.timestamper.TimestamperConfig.xml /usr/share/jenkins/ref/hudson.plugins.timestamper.TimestamperConfig
COPY config.xml /usr/share/jenkins/ref/config.xml 

