FROM jenkins:latest
#JENKINS DE GBB

#USER root
#RUN mkdir /var/log/jenkins
#RUN mkdir /var/cache/jenkins
#RUN chown -R  jenkins:jenkins /var/log/jenkins
#RUN chown -R  jenkins:jenkins /var/cache/jenkins

#USER jenkins

#ENV JAVA_OPTS="-Xmx8192m -Djenkins.install.runSetupWizard=false"
#ENV JENKINS_OPTS="--logfile=/var/log/jenkins/jenkins.log --webroot=/var/cache/jenkins/war"

#installing plugins
#COPY plugins.txt /usr/share/jenkins/ref/plugins.txt
#RUN /usr/local/bin/install-plugins.sh < /usr/share/jenkins/ref/plugins.txt

#applying security
#COPY security.groovy /usr/share/jenkins/ref/init.groovy.d/security.groovy

#adding Maven 353
COPY hudson.tasks.Maven.xml /usr/share/jenkins/ref/hudson.tasks.Maven.xml
COPY jenkins.mvn.GlobalMavenConfig.xml /usr/share/jenkins/ref/jenkins.mvn.GlobalMavenConfig.xml
#COPY tools /usr/share/jenkins/ref/tools
